"""389. Find the Difference
Easy

You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.


Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"
"""


def findTheDifference(self, s: str, t: str) -> str:
    i = 0
    count_dict = {}

    while i < len(t):
        if t[i] not in count_dict:
            count_dict[t[i]] = 1

        else:
            count_dict[t[i]] += 1

        if i < len(s):
            if s[i] not in count_dict:
                count_dict[s[i]] = 1
            else:
                count_dict[s[i]] += 1

        i += 1

    for elem in count_dict:
        if count_dict[elem] % 2 == 1:
            return elem
